### ISSUE TITLE
Branch naming conventions

### ISSUE THREAD

**Issue by k-holland** [catalyst/moodle-mod_reengagement#1]
It's slightly unclear from the Github repository, which branch (naming convention really) to use for Moodle 3.1 and this would possibly compound with future Moodle releases, perhaps a comment in the README to confirm that the master branch is the one to use for the supported 3.1 version or a slight tidy-up perhaps?

**Comment by danmarsden** [comment]
Thanks Karen - the "T" prefixes are actually Totara related branches so I can see how confusing that might be - I'll look at renaming the branches or adding details to the readme.

**Comment by danmarsden** [comment]
I've renamed those "T" prefixed branches to use the word "TOTARA" to help avoid confusion. 

the master branch currently supports both Moodle and Totara from Moodle 2.9 and higher - thanks!
