### ISSUE TITLE
3.9 and 3.11 stable versions pushed to moodle.org?

### ISSUE THREAD

**Issue by GirlieNinja** [catalyst/moodle-mod_reengagement#108]
Would it be possible to have the 3.9 and 3.11 stable versions of the plug-in pushed to moodle.org? We would like to have it installed but normally only pull from moodle.org for plug-ins.

**Comment by danmarsden** [comment]
Hi there - we're in the process of rolling out auto-deployment of our plugins to the plugins db but as we do not rely on the versions in the plugins db we do not regularly publish them (we maintain a lot of plugins.) I'm not sure when we'll get implementing auto-deployment for mod_reengagment but in the meantime you can always get the latest versions of our plugins from our github repos - thanks!
