### ISSUE TITLE
Remove prompt to download mobile app

### ISSUE THREAD

**Issue by rmeske** [catalyst/moodle-mod_reengagement#109]
Hello,

When reengagement emails are sent out the following line is appended to the bottom of the email.
`Reading this in an email? Download the mobile app and receive notifications on your mobile device.`

There should be a setting to make this message optional.

**Comment by alexmorrisnz** [comment]
That message comes from within Moodle and is not a message that this plugin can control, so we cannot add a setting to make it optional.

If you want to disable it for your site you can disable the 'enablemobilewebservice' config setting, or modify the code inside the tool_mobile plugin.
