### ISSUE TITLE
Not sending emails

### ISSUE THREAD

**Issue by AaronH92** [catalyst/moodle-mod_reengagement#11]
I'm testing this plugin to send course suggestions when a user has completed a course, currently set to send with no delay after they have completed the course, but nothing is being sent to my email addresses.  

Inside the '_reengagement' table, I can see the emails are there but not been sent.  [there is an old one in there too which should have sent more than 24 hours ago]

**Comment by danmarsden** [comment]
is cron running correctly on your site?

**Comment by danmarsden** [comment]
closing - no response from reporter.

**Comment by smlavoie** [comment]
Hi Dan, 
I have problem with Reengagement plugin.  Emails are not sent.  At first, I thought something was wrong in activity settings, but when I got a message stating date and time of sent emails in the activity, I knew activity settings were OK.

So I went into different server logs to try to find the source of the problem.  I finally found something in the cron log. Here is the entry:
_Execute scheduled task: Tâche crom de réengagement (mod_reengagement\task\cron_task)
... started 08:00:01. Current memory use 6.9Mo.
... used 39 dbqueries
... used 0.32810091972351 seconds
Scheduled task failed: Tâche crom de réengagement (mod_reengagement\task\cron_task),Erreur de lecture de la base de données_

I removed and reinstalled the plugin. Just to make sure... same kind of entry in the cron log. Can you help me solve the problem?

**Comment by danmarsden** [comment]
can you please enable the global  showcrondebugging setting and provide information on the Moodle version and database type/version you are using. We currently run Postgres ourselves although it should work fine on mysql as well.

please provide this by creating a "new" issue in the github tracker rather than using an old/closed issue.

thanks,
