### ISSUE TITLE
Class 'core_search\area\base_activity' not found

### ISSUE THREAD

**Issue by haasdijk** [catalyst/moodle-mod_reengagement#110]
I installed this mod on one of my test environments with Moodle 3.10 (Build: 20201109) without any problems and the mod worked flawlessly there.

Then I repeated the action on a site of a customer of mine with Moodle 3.9.7 (Build: 20210510). On this installation, when I upgrade the database, I get this message: Class 'core_search\area\base_activity' not found. As a result, I can no longer access site management as an admin. I renamed the folder containing the mod and everything is running again.

Is there a possibility that I can get this running for the customer. Because this is exactly the functionality he is waiting for.

**Comment by danmarsden** [comment]
We have this running on quite a few 3.9 sites, Please make sure you are using the latest version of the code from github and the correct github branch for the version of moodle you are using - see the readme for information on which branch supports each version - then please provide information on the version of reengagment you have installed, turn debugging onto developer level and post the full error trace so we can take a look.

thanks,

**Comment by haasdijk** [comment]
Thanks for your prompt message, Dan. I will be updating this client's site to the latest version of 3.9 in the coming weeks. Then I will try to install the plugin again. If I still have problems, I will get back to you immediately.
Sincerely,
Peter

**Comment by danmarsden** [comment]
I'm closing this for now as I'm not quite convinced that it's a problem with re-engagment and there isn't enough info here for us to check - feel free to comment again if you get more info though and we can reopen it - thanks!
