### ISSUE TITLE
Activity creation is not enabled for manager by default

### ISSUE THREAD

**Issue by jarvil1** [catalyst/moodle-mod_reengagement#111]
Hello,

I have noticed a bug, managers cannot by default create re-engagement-activity, the manager-role is missing 

mod/reengagement:startreengagement
mod/reengagement:editreengagementduration

**Comment by danmarsden** [comment]
startreengagment should only be given to the student role by default - it controls who should be included in the re-engagment process. the editreengagmentduration should be given to managers by default as mentioned in #112  - thanks!
