### ISSUE TITLE
After creating activity with manager role "This reengagement is not available"

### ISSUE THREAD

**Issue by jarvil1** [catalyst/moodle-mod_reengagement#112]
Hello,

after creating the activity with manager-role it displays "This reengagement is not available" whis is this?

**Comment by danmarsden** [comment]
Thanks for the report - the manager role should also have the reengagement:editreengagementduration so I have added a patch to github to add that to the default configuration, in the meantime you may need to add this capability to the manager role manually. 

thanks!
