### ISSUE TITLE
Error in Moodle 3.9

### ISSUE THREAD

**Issue by sciamano69** [catalyst/moodle-mod_reengagement#116]
Hi,

I configured the reengagement plugin and I get this message (never saw before). 

Notice: Undefined variable: perpagevisible in /var/www/html/moodle/mod/reengagement/view.php on line 172

Notice: Undefined variable: perpagestring in /var/www/html/moodle/mod/reengagement/view.php on line 178

Notice: Undefined variable: perpagesize in /var/www/html/moodle/mod/reengagement/view.php on line 181

I debug info there is also this message:

Too much data passed as arguments to js_call_amd("core_user/participants", "init"). Generally there are better ways to pass lots of data from PHP to JavaScript, for example via Ajax, data attributes, ... . This warning is triggered if the argument string becomes longer than 1024 characters.

line 1058 of /lib/outputrequirementslib.php: call to debugging()
line 232 of /mod/reengagement/view.php: call to page_requirements_manager->js_call_amd()
Can you help me please?

**Comment by danmarsden** [comment]
thanks for the report - this has been fixed in the latest version available here in github. We'll look to publish this to the moodle.org plugins db next time we are updating the plugins.
