### ISSUE TITLE
Completion time at 01/01/1970

### ISSUE THREAD

**Issue by GabGuev** [catalyst/moodle-mod_reengagement#124]
Hello,
In the database the completiontime empty is at 0, the code considers it like a timestamp so when it formats it, it gives 1/01/1970 

![image](https://user-images.githubusercontent.com/107034648/193245812-dd47e43f-26b4-4d02-96cf-ece6ee2d4a71.png)

It this line that poses a problem:
https://github.com/catalyst/moodle-mod_reengagement/blob/34355e5235688ca839ec907abf0d540994cf74a1/classes/table/reengagement_participants.php#L423

I propose this correction :
`return $data->completiontime ? userdate($data->completiontime, get_string('strftimedatetimeshort', 'langconfig')) : '-';`

For have that instead:
![image](https://user-images.githubusercontent.com/107034648/193246272-bc84a485-26ae-4990-be9d-b0d64b73b6d8.png)

Thanks  😃

**Comment by danmarsden** [comment]
thanks for the report, feel free to submit a pull request with that change otherwise it may sit here for a while.

**Comment by danmarsden** [comment]
thanks for the PR! - flagging this as closed.

**Comment by GabGuev** [comment]
Thanks @danmarsden! I'm glad to have contributed :)
