### ISSUE TITLE
Add reengagement trigger as join to a cohort

### ISSUE THREAD

**Issue by jasimp** [catalyst/moodle-mod_reengagement#128]
Hi 
It will be a better option if you can add the re engagement activity triggering when a user added to a cohort
There is Cohort based access restriction plug in. but that not working with reengagement.

**Comment by danmarsden** [comment]
Thanks for your feedback - we don't have any plans to adjust the re-engagement plugin to listen to other types of events other than activity completion so I'm closing this as "won't fix" for now but if you have internal development capabilities feel free to submit a pull request anyway and we'll consider it.
thanks!
