### ISSUE TITLE
Debugging warning message in view page

### ISSUE THREAD

**Issue by omanpaur8** [catalyst/moodle-mod_reengagement#133]
After creating a reengagement activity or when you access the view page, you will get the following debug message if debugging is enabled.

`Debugging: Too much data passed as arguments to js_call_amd("core_user/participants", "init"). Generally there are better ways to pass lots of data from PHP to JavaScript, for example via Ajax, data attributes, ... . This warning is triggered if the argument string becomes longer than 1024 characters. in ./lib/outputrequirementslib.php on line 1091.
Stack trace:
line 1091 of ./lib/outputrequirementslib.php: call to debugging()
line 234 of ./mod/reengagement/view.php: call to page_requirements_manager->js_call_amd()`

This was observed in Moodle 3.9.22+ (Build: 20230721) and in Moodle 4.3dev (Build: 20230728).

**Comment by danmarsden** [comment]
probably just copied from how upstream/core did this at some point... I'd guess from report/participation/index.php in an older release...  feel free to submit a pull request with a fix!
