### ISSUE TITLE
Cron task default schedule interval

### ISSUE THREAD

**Issue by pefo5543** [catalyst/moodle-mod_reengagement#136]
It seems to be conflicting information regarding default/recommended schedule interval for the cron task.
In moodle plugin documentation https://docs.moodle.org/400/en/Reengagement_activity is stated that "Re-engagement relies on a cron task which set by default to run every hour"
But in code the default interval for the task is set to run every 5 minutes.

**Comment by danmarsden** [comment]
Thanks for the report - keep in mind the docs.moodle.org site is a wiki and you are welcome to help by improving the documentation yourself! - just login and update the content :-)

I've updated the text on that page now so closing this off.
