### ISSUE TITLE
Re-engagement activity - Participants not correctly marked as complete

### ISSUE THREAD

**Issue by johnnylupino** [catalyst/moodle-mod_reengagement#140]
Hi guys,

Thank you for this plugin.

I'd like to report an issue spotted with course participants incorrectly marked as complete in the re-engagement activity when duration time is changed.
Please see the below steps to replicate:

1. create two assignments
2. create two re-engagements
3. restrict access to re-engagements based on assignment completions, assignment 1 - re-engagement 1 and 
assignment 2 - re-engagement 2 respectively
5. set re-engagements duration to 5 minutes
6. login as user and complete assignment 1, wait 5 minutes for the re-engagement 1 to complete 
7. login as admin and edit re-engagement 2 duration from 5 minutes (after completing assignment 2)  to 4 minutes and save
8. check activity completions for the user - both re-engagements are now complete despite the fact that the user has never completed the assignment 2

Tested in Vanila Moodle 4.1.6

Hopefully you will be able to reproduce it.

All the Best,
Archie

**Comment by danmarsden** [comment]
fixed in #149
