### ISSUE TITLE
Only 236 members are sent a mail

### ISSUE THREAD

**Issue by schoenerw** [catalyst/moodle-mod_reengagement#141]
Hello there,

great tool you made. 

We used this to create a course as advent calendar. There are 24 topics, for each day one topic. 
Every other day the corresponding topic is unlocked at 00:01 am.
Each topic contains 1 reengagement activity, which sends a mail to the course members at 6:00 am on the corresponding day.

There are over 600 members in the course. I checked the log files for 2 days. Only about 236 emails are sent at 6:00 am to members. The other members get no email. It seams, that every day onother pool of members gets an email.

Are there any restrictions, we dont know of?
Is there a way we can bypass this problem?
Thank you

Wolfgang

**Comment by danmarsden** [comment]
there are no restrictions built into the Re-engagement plugin that would cause this, however your hosting provider may limit the amount of email you are allowed to send in a short time frame - check out your scheduled task logs and see if the re-engagment task is reporting any issues while it's sending the emails out?

**Comment by schoenerw** [comment]
There doesnt seem to be a restriction in our server tasks. We sometimes send mails to thousands of users with moodle.

I searched in the database for ideas.
There is a table "mdl_reengagement_inprogress". In this table are 236 items for our reengagement 19, which was the activity, that worked this morning. All items have a emailsent=1. 
But there are still 460 members left in the course who are missing in this mdl_reengagement_inprogress table. 
Do you have a hint, why these other members are missing in this table? 
I thought, that we configured the activities correctly. 

Thank you
Wolfgang
