### ISSUE TITLE
Duplicate of Reengagement activity 

### ISSUE THREAD

**Issue by lythro10** [catalyst/moodle-mod_reengagement#147]
The issue we are currently facing with the duplication of the activity is that within the settings - Notification content(User)  we have a href with the URL of another course within the same Moodle. 

Once the re-engagement activity is duplicated either on the same course or within another course the origin of the webpage is removed from the href. 

Please see below 

Original  = href="https://sample.com/course/view.php?id=20#section-11

Coplied = href="$@COURSEVIEWBYID*20@$#section-11

**Comment by danmarsden** [comment]
this appears to be a duplicate of #132 - please makre sure you are using reengagment version 2023020804 - (the latest version) - I'm closing this off but feel free to re-open this if you are already using that release and / or have further information.

thanks!
