### ISSUE TITLE
Very huge icon in course

### ISSUE THREAD

**Issue by jdoublestorm** [catalyst/moodle-mod_reengagement#17]
![screenshot-reengage](https://cloud.githubusercontent.com/assets/25032622/21807130/7b5961cc-d73d-11e6-99b4-f6f95a0bda15.png)

**Comment by danmarsden** [comment]
What Moodle version and what theme are you using?

**Comment by jdoublestorm** [comment]
Hi Dan,
This used within Totara, but built on top of moodle version:

Totara LMS utilises the following copyrighted material:
Moodle<http://moodle.org/> 3.0.6 (Build: 20160912)<http://docs.moodle.org/dev/Releases>

And the theme comes std frpm Totara called:
Basis (probably not the same in moodle)

But I be happy to assist you with testing in totara

Regards
Jesper

**Comment by danmarsden** [comment]
we do have separate Totara branches here in github which don't include the newer icon - (we should probably cherry-pick that across though.)

**Comment by danmarsden** [comment]
I've just added a commit to the Totara 9 branch to use their flex icons code. It's not exactly the same as our new reengagement icon which is the flipped version of the "history" icon from the Font-awesome pack. it doesn't look like the Totara flex-icons stuff includes the css required to flip the icon - in future we might add it to the custom css in the reengagement code.
