### ISSUE TITLE
Reengament Issue - Coding error

### ISSUE THREAD

**Issue by SensCyPez** [catalyst/moodle-mod_reengagement#175]
Hello,

We have been using this plug-in for awhile and have not had any issues until today (see screenshot below).

As of right now, it appears as if the reminders have not been sent out.

Do you know what is going on here, and how we can fix it?

Thanks,
Michael

![codingerror](https://github.com/user-attachments/assets/90e6daa9-a7aa-4241-94f1-0e732bbf8f5c)

**Comment by SensCyPez** [comment]
Hey guys, can you please have a quick look at this because it is a coding error. Please respond with a solution.

**Comment by danmarsden** [comment]
Have.you checked to see if you have the latest version of reengagement installed for your moodle version? What moodle version are you using and what version of reengagement do you have installed?

**Comment by SimonThornett** [comment]
@danmarsden was asked to look at this in WR#442991. I have created a pull request here:

#176 

The issue is that the `flexible_table` class has a requirement on the method `has_capability` if the table is an instance of `dynamic`. Currently it only displays that worning above, however this will be enforced for Moodle 4.5

**Comment by danmarsden** [comment]
@SimonThornett - the older code was based on the dynamic table class but in 01be5e0106b6e82302be4d82b3dc142624b7ac7d it was changed to use the participants class as the base - do you have the latest code in place?

**Comment by SimonThornett** [comment]
Apologies @danmarsden, I've confirmed that this was already fixed and closed the pull request.

**Comment by danmarsden** [comment]
all good! - Thanks for confirming that it's all working! - it wasn't easy to find/identify in the commit history as I patched this and released the new version before the upstream security release came out.
