### ISSUE TITLE
Error if showdescription somehow gets set to true

### ISSUE THREAD

**Issue by heather-williams** [catalyst/moodle-mod_reengagement#18]
I experienced an issue with the cron for this plug in giving the following error:

```
Scheduled task failed: Reengagement cron task (mod_reengagement\task\cron_task),Error reading from database
Scheduled task exception: Reengagement cron task - Error reading from database Debug: Unknown column 'intro' in 'field list'
SELECT name, intro, introformat FROM mdl_reengagement WHERE id = ?
[array (
  0 => '2',
)]
Error code: dmlreadexception
* line 445 of /lib/dml/moodle_database.php: dml_read_exception thrown
* line 1094 of /lib/dml/mysqli_native_moodle_database.php: call to moodle_database->query_end()
* line 1496 of /lib/dml/moodle_database.php: call to mysqli_native_moodle_database->get_records_sql()
* line 1468 of /lib/dml/moodle_database.php: call to moodle_database->get_record_sql()
* line 1447 of /lib/dml/moodle_database.php: call to moodle_database->get_record_select()
* line 1151 of /course/lib.php: call to moodle_database->get_record()
* line 618 of /lib/modinfolib.php: call to get_array_of_activities()
* line 451 of /lib/modinfolib.php: call to course_modinfo::build_course_cache()
* line 412 of /lib/modinfolib.php: call to course_modinfo->__construct()
* line 2078 of /lib/modinfolib.php: call to course_modinfo::instance()
* line 628 of /mod/reengagement/lib.php: call to get_fast_modinfo()
* line 219 of /mod/reengagement/lib.php: call to reengagement_get_startusers()
* line 52 of /mod/reengagement/classes/task/cron_task.php: call to reengagement_crontask()
* line 75 of /lib/cronlib.php: call to mod_reengagement\task\cron_task->execute()
* line 61 of /admin/cli/cron.php: call to cron_run()
```

This appears to be because Moodle is looking for a modname_get_coursemodule_info function for the module and if it does not exist, it checks to see if showdescription is set in the course_modules table for that module's instances and if so, it looks for a 'intro' and 'introformat' field in the module's table.

I'm not sure what setting caused showdescription to equal true for one of my instances, because I can't find the setting that controls that for this module, but one was set to true, which makes me think it is somehow possible.

I think a good solution here would be to add the modname_get_coursemodule_info function to the code.

**Comment by danmarsden** [comment]
Thanks Heather - it would be better if we could work out how that value was set when we don't provide the interface for it. Many of the core plugins don't implement the modname_get_coursemodule_info function so it shouldn't be a requirement.

What version of Moodle/Totara are you using? - and what version of the re-engagement plugin are you using? - the line numbers don't seem to match with our latest code.

**Comment by danmarsden** [comment]
I just remembered, earlier versions of this plugin included the intro editor in the editing form (even though the intro field didn't exist in the reengagement activity and didn't actually save the intro text) - this would have meant that the option to set showdescription would have been in the form as well.

It might be worth adding a step in the upgrade file to reset any activities with showdescription set to true and make them set to false.

**Comment by danmarsden** [comment]
or alternatively we could add the intro field to the table, and add the intro field back to the editor. @eugeneventer do you have any thoughts on this?

**Comment by eugeneventer** [comment]
@danmarsden Hmm, i don't think adding the intro field adds any value, as this plugin operates in the background really ;)
My preference would be to go for the upgrade step that ensures all 'showdescription' values are false.

**Comment by actXc** [comment]
The Intro-Field could help to describe the idea behind the specific reengagement for later course maintainers.

**Comment by mgancarzdsi** [comment]
I came upon this issue while googling around for an error that was coming up for the re-engagement activity during the global search indexing cron. The error message is below with siteurl replaced with sitedomain, and it also seems to be related to the intro / introformat fields not existing. I found this related post: https://moodle.org/mod/forum/discuss.php?d=252126 but the only mention of "FEATURE_MOD_INTRO" in the documentation is at https://docs.moodle.org/dev/Activity_modules and mentions it's expected by Moodle now?

> Execute scheduled task: Global search indexing (core\task\search_index_task)
> ... started 00:00:01. Current memory use 16.4MB.
> Processing area: Assignment - activity information
>   No new documents to index.
> <snipped extra uninteresting bits>
> Processing area: Reengagement - activity information
> PHP Notice:  Undefined property: stdClass::$intro in /var/www/html/sitedomain/search/classes/base_activity.php on line 107
> PHP Notice:  Undefined property: stdClass::$introformat in /var/www/html/sitedomain/search/classes/base_activity.php on line 107
>   No new documents to index.

**Comment by danmarsden** [comment]
this should be resolved now hopefully - description is not a required field in moodle, and this plugin doesn't currently implement it - closing this one off, but feel free to comment here if it still presents a problem for you and we can take another look.
