### ISSUE TITLE
Unable to restore course containing reengagement instance on M32

### ISSUE THREAD

**Issue by logan-reynolds** [catalyst/moodle-mod_reengagement#21]
When attempting to restore a course containing an instance of mod_reengagement version 2016112400 release 3.2.1 on Moodle 3.2.2 (Build: 20170313) I get the following error which indicates the 'thirdpartyemails' field needs to be included in the activity backup/restore.  This is a problem because the user will not know that their course backup cannot be restored until they try later (i.e. no warnings are present during backup, it just finishes backup successfully):

Error writing to database

More information about this error

×Debug info: Field 'thirdpartyemails' doesn't have a default value
INSERT INTO mdl_reengagement (name,timecreated,timemodified,emailuser,emailsubject,emailcontent,emailcontentformat,duration,suppresstarget,emaildelay,emailrecipient,emailsubjectmanager,emailcontentmanager,emailcontentmanagerformat,course) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
[array (
0 => 'testreengagement',
1 => 1489538729,
2 => '0',
3 => '0',
4 => '',
5 => 'This is a reminder email from course %coursename%.',
6 => '1',
7 => '300',
8 => '0',
9 => '604800',
10 => '0',
11 => '',
12 => '',
13 => '0',
14 => 3,
)]
Error code: dmlwriteexception
×Stack trace:
line 482 of /lib/dml/moodle_database.php: dml_write_exception thrown
line 1259 of /lib/dml/mysqli_native_moodle_database.php: call to moodle_database->query_end()
line 1305 of /lib/dml/mysqli_native_moodle_database.php: call to mysqli_native_moodle_database->insert_record_raw()
line 70 of /mod/reengagement/backup/moodle2/restore_reengagement_stepslib.php: call to mysqli_native_moodle_database->insert_record()
line 137 of /backup/util/plan/restore_structure_step.class.php: call to restore_reengagement_activity_structure_step->process_reengagement()
line 103 of /backup/util/helper/restore_structure_parser_processor.class.php: call to restore_structure_step->process()
line 178 of /backup/util/xml/parser/processors/grouped_parser_processor.class.php: call to restore_structure_parser_processor->dispatch_chunk()
line 91 of /backup/util/helper/restore_structure_parser_processor.class.php: call to grouped_parser_processor->postprocess_chunk()
line 148 of /backup/util/xml/parser/processors/simplified_parser_processor.class.php: call to restore_structure_parser_processor->postprocess_chunk()
line 92 of /backup/util/xml/parser/processors/progressive_parser_processor.class.php: call to simplified_parser_processor->process_chunk()
line 190 of /backup/util/xml/parser/progressive_parser.class.php: call to progressive_parser_processor->receive_chunk()
line 278 of /backup/util/xml/parser/progressive_parser.class.php: call to progressive_parser->publish()
line ? of unknownfile: call to progressive_parser->end_tag()
line 179 of /backup/util/xml/parser/progressive_parser.class.php: call to xml_parse()
line 158 of /backup/util/xml/parser/progressive_parser.class.php: call to progressive_parser->parse()
line 110 of /backup/util/plan/restore_structure_step.class.php: call to progressive_parser->process()
line 181 of /backup/util/plan/base_task.class.php: call to restore_structure_step->execute()
line 201 of /backup/moodle2/restore_activity_task.class.php: call to base_task->execute()
line 177 of /backup/util/plan/base_plan.class.php: call to restore_activity_task->execute()
line 167 of /backup/util/plan/restore_plan.class.php: call to base_plan->execute()
line 335 of /backup/controller/restore_controller.class.php: call to restore_plan->execute()
line 224 of /backup/util/ui/restore_ui.class.php: call to restore_controller->execute_plan()
line 111 of /backup/restore.php: call to restore_ui->execute()

**Comment by danmarsden** [comment]
Thanks Logan, looks like there are a few fields missing from that file - we'll get this fixed asap.
