### ISSUE TITLE
Can not duplicate instance 

### ISSUE THREAD

**Issue by actXc** [catalyst/moodle-mod_reengagement#23]
same as in #21 

Debug info:
Field 'thirdpartyemails' doesn't have a default value INSERT INTO mdl_reengagement (name,timecreated,timemodified,emailuser,emailsubject,emailcontent,emailcontentformat,duration,suppresstarget,emaildelay,emailrecipient,emailsubjectmanager,emailcontentmanager,emailcontentmanagerformat,course) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) [array ( 0 => 'Erinnerung', 1 => 1491255586, 2 => '0', 3 => '2', 4 => 'Jetzt ist die nächste Frage drann...', 5 => 'This is a reminder email from course %coursename%.', 6 => '1', 7 => '300', 8 => '0', 9 => '300', 10 => '0', 11 => '', 12 => '', 13 => '0', 14 => '4', )] Error code: dmlwriteexception

* line 482 of /lib/dml/moodle_database.php: dml_write_exception thrown
* line 1259 of /lib/dml/mysqli_native_moodle_database.php: call to moodle_database->query_end()
* line 1305 of /lib/dml/mysqli_native_moodle_database.php: call to mysqli_native_moodle_database->insert_record_raw()
* line 70 of /mod/reengagement/backup/moodle2/restore_reengagement_stepslib.php: call to mysqli_native_moodle_database->insert_record()
* line 137 of /backup/util/plan/restore_structure_step.class.php: call to restore_reengagement_activity_structure_step->process_reengagement()
* line 103 of /backup/util/helper/restore_structure_parser_processor.class.php: call to restore_structure_step->process()
* line 178 of /backup/util/xml/parser/processors/grouped_parser_processor.class.php: call to restore_structure_parser_processor->dispatch_chunk()
* line 91 of /backup/util/helper/restore_structure_parser_processor.class.php: call to grouped_parser_processor->postprocess_chunk()
* line 148 of /backup/util/xml/parser/processors/simplified_parser_processor.class.php: call to restore_structure_parser_processor->postprocess_chunk()
* line 92 of /backup/util/xml/parser/processors/progressive_parser_processor.class.php: call to simplified_parser_processor->process_chunk()
* line 190 of /backup/util/xml/parser/progressive_parser.class.php: call to progressive_parser_processor->receive_chunk()
* line 278 of /backup/util/xml/parser/progressive_parser.class.php: call to progressive_parser->publish()
* line ? of unknownfile: call to progressive_parser->end_tag()
* line 179 of /backup/util/xml/parser/progressive_parser.class.php: call to xml_parse()
* line 158 of /backup/util/xml/parser/progressive_parser.class.php: call to progressive_parser->parse()
* line 110 of /backup/util/plan/restore_structure_step.class.php: call to progressive_parser->process()
* line 181 of /backup/util/plan/base_task.class.php: call to restore_structure_step->execute()
* line 201 of /backup/moodle2/restore_activity_task.class.php: call to base_task->execute()
* line 177 of /backup/util/plan/base_plan.class.php: call to restore_activity_task->execute()
* line 167 of /backup/util/plan/restore_plan.class.php: call to base_plan->execute()
* line 335 of /backup/controller/restore_controller.class.php: call to restore_plan->execute()
* line 3311 of /course/lib.php: call to restore_controller->execute_plan()
* line 3238 of /course/lib.php: call to duplicate_module()
* line 118 of /course/rest.php: call to mod_duplicate_activity()

Debug info:
Field 'thirdpartyemails' doesn't have a default value INSERT INTO mdl_reengagement (name,timecreated,timemodified,emailuser,emailsubject,emailcontent,emailcontentformat,duration,suppresstarget,emaildelay,emailrecipient,emailsubjectmanager,emailcontentmanager,emailcontentmanagerformat,course) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) [array ( 0 => 'Erinnerung', 1 => 1491255586, 2 => '0', 3 => '2', 4 => 'Jetzt ist die nächste Frage drann...', 5 => 'This is a reminder email from course %coursename%.', 6 => '1', 7 => '300', 8 => '0', 9 => '300', 10 => '0', 11 => '', 12 => '', 13 => '0', 14 => '4', )] Error code: dmlwriteexception

**Comment by danmarsden** [comment]
yeah - closing this as a duplicate - we'll try to get to this very soon, thanks.
