### ISSUE TITLE
Error when I add Reengagement

### ISSUE THREAD

**Issue by balu1984** [catalyst/moodle-mod_reengagement#25]
I want to add one reengagement into the course but not success.
Moodle version: 3.3
Reengagement version: 3.3.1 2017050800

I changed the column type VARCHAR and after work, but I dont know if it is going to cause trouble in the future.

Debug info: Column 'visibleoncoursepage' cannot be null
INSERT INTO mdl_course_modules (course,module,instance,visible,visibleoncoursepage,visibleold,idnumber,groupmode,groupingid,completion,completiongradeitemnumber,completionview,completionexpected,availability,showdescription,added) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
[array (
0 => '10',
1 => 26,
2 => 0,
3 => 0,
4 => NULL,
5 => 0,
6 => '',
7 => 0,
8 => 0,
9 => 2,
10 => NULL,
11 => 0,
12 => 0,
13 => NULL,
14 => 0,
15 => 1495716800,
)]
Error code: dmlwriteexception
Stack trace:
line 489 of /lib/dml/moodle_database.php: dml_write_exception thrown
line 1259 of /lib/dml/mysqli_native_moodle_database.php: call to moodle_database->query_end()
line 1305 of /lib/dml/mysqli_native_moodle_database.php: call to mysqli_native_moodle_database->insert_record_raw()
line 830 of /course/lib.php: call to mysqli_native_moodle_database->insert_record()
line 108 of /course/modlib.php: call to add_course_module()
line 154 of /course/modedit.php: call to add_moduleinfo()

**Comment by danmarsden** [comment]
thanks for the report - I didn't see that in my earlier testing on 3.3 but I might not have added a new re-engagement... I'll try to add a behat test for this too.

**Comment by danmarsden** [comment]
I've just pushed in a fix that should sort that for you now - you should revert the change you made to the core course_modules table as it will definitely cause problems in future.

**Comment by balu1984** [comment]
Thank you for the fast response, I try now working.
