### ISSUE TITLE
Email reply variable question

### ISSUE THREAD

**Issue by k-holland** [catalyst/moodle-mod_reengagement#3]
The email sent to users from my test server has a no reply for reply address, although I have the support contact email configured, which can mean they're filtered as spam, is there any way to avoid this? Is this a server setting only? 
from:	3.1 Site <noreply@debian>
reply-to:	Do not reply to this email <noreply@debian>

**Comment by danmarsden** [comment]
thanks - I've pusshed a fix that might sort this but I'll try to test it sometime.

**Comment by danmarsden** [comment]
this seems to work better now as well - if anyone has any issues with this we can reopen again!
