### ISSUE TITLE
Error reading from the database

### ISSUE THREAD

**Issue by angiemr** [catalyst/moodle-mod_reengagement#30]
I have a question about the operation of this plugin. We test it in courses with 400 people and everything was ok but when we test it in one of our big courses (30.000 enrolled users), it died. The people don't receive the email and we obtain an error that says "Error reading from the database". Do you have any idea what may be happening and how could we solve it?

**Comment by danmarsden** [comment]
Hi @angiemr, please make sure you are using the latest version of the plugin from github here, and then increase your debugging level so that more information is displayed so we can help diagnose this further. thanks.

**Comment by danmarsden** [comment]
closing due to lack of response and not enough information that allows us to reproduce.
