### ISSUE TITLE
Error when adding a reengagement - undefined function

### ISSUE THREAD

**Issue by pjcevans** [catalyst/moodle-mod_reengagement#38]
Hey folks, the reengagement activity still sends out an email but there is no info about when emails were sent + to whom etc and this error displays on the reengagement's page. Using the latest version (d38635acfe7e2036412f62ae90a25aacc213a61d) & just creating a reengagement that sends an email after 5 minutes, everything else default.

Here's the error:

```
Debug info: 
Error code: generalexceptionmessage
×Stack trace:
line 253 of \mod\reengagement\classes\table\participants.php: Error thrown
line 226 of \mod\reengagement\view.php: call to mod_reengagement\table\participants->__construct()
```

It looks as if a function from locallib.php (get_viewable_roles) is being called but locallib isn't being included within classes/table/participants.php

Cheers, hope that helps

**Comment by danmarsden** [comment]
Thanks for the report - that's a function only in 3.5 - I've removed it from the 3.4 branch so hopefully should be working a bit better now? (haven't tested it yet but will try later today)

**Comment by pjcevans** [comment]
No problem - that seems to have fixed it! Thanks :)
