### ISSUE TITLE
How to use the release functionality

### ISSUE THREAD

**Issue by k-holland** [catalyst/moodle-mod_reengagement#4]
I found the documentation overall very clear but on the ability to release activities based on the Reengagement activity, I wasn't able to set one up in the way I thought it would work.
If you have an assignment task 1, and assignment task 2, how to set up a reengagement activity based on task 1 completion to release task 2 access, a small step by step on this configuration would be great!

**Comment by danmarsden** [comment]
Hi Karen - did you see the docs linked on the plugin? - we mentioned timed release here:
https://docs.moodle.org/31/en/Reengagement_activity#Timed_release

(but it could probably do with some improvements)

**Comment by peterbulmer** [comment]
I did make some improvements to the timed release section after seeing Karen's comments.

I _think_ I've made it more clear, but it's hard for me to say, since it makes sense to those who wrote it.

**Comment by danmarsden** [comment]
hah - cool, yes it does look better to me too.

**Comment by danmarsden** [comment]
Karen - let us know if you still can't make sense of it and we'll re-open/look at it further!
