### ISSUE TITLE
reengagement observing restrict access rules

### ISSUE THREAD

**Issue by erinkmelvin** [catalyst/moodle-mod_reengagement#41]
Hello!  I'm not sure how or where to fix this, but I would like to see the reengagement plugin 'observe' the restrict access rules.  

**Use Case:**
A course that is built with two separate groups that have both shared content and topic sections that are shown/hidden using restrict access and groups.  Currently, all learners are emailed regardless of whether they can see the topic section/activities or not.  

I have two test students in the pre-k section and one student in the infant/toddler section.  All three students received the messages set in both sections. (see image)

Ideally, only the students who have access to the activities/section will receive the emails.  

![reengagement](https://user-images.githubusercontent.com/38115942/38391894-869c4d9c-38da-11e8-8b72-27ce28a0de97.png)

Can you get me started with how to add this functionality?

Thanks, 

Erin

**Comment by danmarsden** [comment]
It should be doing that already - although if you added the content restriction after creating the reengagment that might have caused a problem?

First the activity gets a list of all users that are enrolled and have the capability reengagement:startreengagement in the reenagement - see:
https://github.com/catalyst/moodle-mod_reengagement/blob/master/lib.php#L708

then it checks if the user can "see" the activity which should fail if restrict access rules are in place.
https://github.com/catalyst/moodle-mod_reengagement/blob/master/lib.php#L748

but... if that process has run prior to you setting up the content restriction rules it may have already included the users in the list.

when we send the notification we check to make sure the user is still enrolled:
https://github.com/catalyst/moodle-mod_reengagement/blob/master/lib.php#L278

but we should probably add another check there to make sure they can still "see" the reengagment as well. Feel free to submit a pull request!

**Comment by erinkmelvin** [comment]
Thanks Dan.  I wondered if that was an issue in my testing.  I'll give it another shot and make sure I do it in order!

**Comment by danmarsden** [comment]
still room for improvement there though - we should be checking the user can still see the reengagment before sending the actual notification.

**Comment by erinkmelvin** [comment]
Hi Dan, I was placing the restrict access against the topic, not the actual reengagement plugin, thinking that hiding the topic would hide the activities in it.  Placing restrict access on the reengagement activity worked.  

Thanks!

**Comment by nicogaldo** [comment]
> Hi Dan, I was placing the restrict access against the topic, not the actual reengagement plugin, thinking that hiding the topic would hide the activities in it. Placing restrict access on the reengagement activity worked.
> 
> Thanks!

Do you have group restrictions? I can't get it to work.
