### ISSUE TITLE
latest M3.3 / 34+ versions encountering errors on Totara 12

### ISSUE THREAD

**Issue by logan-reynolds** [catalyst/moodle-mod_reengagement#48]
When viewing a course with the latest Moodle 3.3 version 2017102004 or 3.4 version 2017122005 installed on Totara 12, I see the following with debugging on:
```
The module reengagement does not define the standard capability mod/reengagement:addinstance
    line 2078 of /course/lib.php: call to debugging()
    line 674 of /course/lib.php: call to course_allowed_module()
    line 320 of /course/renderer.php: call to get_module_metadata()
    line 866 of /course/format/renderer.php: call to core_course_renderer->course_section_add_cm_control()
    line 56 of /course/format/topics/format.php: call to format_section_renderer_base->print_multiple_section_page()
    line 288 of /course/view.php: call to require()
```
When trying to add a reengagement instance in a course I get the following errors which prevent it from being accessed/configured after being added to course:
```
Capability "mod/reengagement:startreengagement" was not found! This has to be fixed in code.
    line 418 of /lib/accesslib.php: call to debugging()
    line 81 of /mod/reengagement/view.php: call to has_capability()

Capability "mod/reengagement:editreengagementduration" was not found! This has to be fixed in code.
    line 418 of /lib/accesslib.php: call to debugging()
    line 82 of /mod/reengagement/view.php: call to has_capability()

Coding error detected, it must be fixed by a programmer: notlocalisederrormessage
Debug info: error
Error code: codingerror
Stack trace:
    line 858 of /lib/deprecatedlib.php: coding_exception thrown
    line 85 of /mod/reengagement/view.php: call to error()

Coding error detected, it must be fixed by a programmer: Unknown method called against core_user_renderer :: unified_filter
Debug info:
Error code: codingerror
Stack trace:
    line 138 of /lib/outputrenderers.php: coding_exception thrown
    line 215 of /mod/reengagement/view.php: call to plugin_renderer_base->__call()
```

Noting neither of these errors occur on latest Moodle 3.5 using latest version 2017122005, so these errors appear to be Totara-specific and I wasn't sure whether that's a supported platform

**Comment by danmarsden** [comment]
pretty sure those are defined in db/access.php in both versions - maybe there's a permissions error on your totara install preventing db/access.php from being read by the web server?

I don't think anyone here has tested it in totara 12 yet, but there's also the "TOTARA_10" branch here on github that might be the better branch to use for Totara installs.

**Comment by logan-reynolds** [comment]
thank you; just passing along the info that I tested again and this error also seems to happen using that latest version in the TOTARA_10 branch, so this appears to be something affected by something that's changed in core Totara 12.  I'll post any further info I find and will watch future releases to see if they resolve the problem on T12 at a later date.

**Comment by danmarsden** [comment]
we haven't seen this on our T12 branch - and t10 is not a supported release (by us anyway) so I'm closing this off.
