### ISSUE TITLE
Error when trying to setup phpunit

### ISSUE THREAD

**Issue by kiklop74** [catalyst/moodle-mod_reengagement#51]
Setup: docker image moodlehq/moodle-php-apache:7.0
Moodle version 3.5.2

The setup goes just fine. However when I try to setup phpunit environment I get the following:

    Default exception handler: Cannot be executed during upgrade Debug: 
    Error code: cannotexecduringupgrade
    * line 1443 of /lib/setuplib.php: moodle_exception thrown
    * line 2159 of /lib/modinfolib.php: call to upgrade_ensure_not_running()
    * line 905 of /course/lib.php: call to get_fast_modinfo()
    * line 948 of /course/lib.php: call to course_create_sections_if_missing()
    * line 22 of /mod/oublog/settings.php: call to course_add_cm_to_section()
    * line 89 of /lib/classes/plugininfo/mod.php: call to include()
    * line 47 of /admin/settings/plugins.php: call to core\plugininfo\mod->load_settings()
    * line 7999 of /lib/adminlib.php: call to require()
    * line 8101 of /lib/adminlib.php: call to admin_get_root()
    * line 35 of /mod/reengagement/db/install.php: call to admin_write_settings()
    * line 782 of /lib/upgradelib.php: call to xmldb_reengagement_install()
    * line 512 of /lib/upgradelib.php: call to upgrade_plugins_modules()
    * line 1857 of /lib/upgradelib.php: call to upgrade_plugins()
    * line 491 of /lib/installlib.php: call to upgrade_noncore()
    * line 461 of /lib/phpunit/classes/util.php: call to install_cli_database()
    * line 150 of /admin/tool/phpunit/cli/util.php: call to phpunit_util::install_site()

I think that the problem is in `xmldb_reengagement_install` function which looks like this:

    function xmldb_reengagement_install() {
        $settings = array('s__enablecompletion' => 1, 's__enableavailability' => 1);
        admin_write_settings($settings);

        return true;
    }

I think it should look like this:

    function xmldb_reengagement_install() {
        set_config('enablecompletion', 1);
        set_config('enableavailability', 1);
        return true;
    }

**Comment by danmarsden** [comment]
that looks weird... who wrote that!  I'd be more inclined to remove that completely and make sure we are showing an error when someone tries to create an activity and completion/availability are disabled. Quitely enabling settings like this during installation makes me very uncomfortable.....

**Comment by danmarsden** [comment]
dropped a fix for this into master - will look at backporting later - thanks!
