### ISSUE TITLE
Reengagement date and time inconsistency

### ISSUE THREAD

**Issue by valeriia-s** [catalyst/moodle-mod_reengagement#56]
Our customer decided to start using the reengagement activity with the already created course, it has lots of users enrolled into it.

The goal is to email the user with a delay based on the user enrolment date.

The activity works fine with the newly enrolled users, the date and time of the reengagement are calculated correctly for them.

For the users who were enrolled before the reengagement activity was created, their reengagement date and time are calculated incorrectly. The activity just adds a delay time to the time the activity was created.

Example:

Course was created on 18/06/19
User A was enrolled into the course on 18/06/19
Reengagement activity with 5 days delay based on the user enrolment date was created on 20/06/19
User B was enrolled into the course on 20/06/19

In this scenario user A will be emailed on 25/06/19, user B will be emailed on 25/06/19 as well.

Your feedback would be much appreciated.

**Comment by danmarsden** [comment]
Hi there,

the re engagement activity has a bulk change tool on the view.php allowing you to select users an update their recompletion dates which can be used to fix this.

thanks,
