### ISSUE TITLE
Cant install error in version.php file.

### ISSUE THREAD

**Issue by neeesn** [catalyst/moodle-mod_reengagement#58]
When i download from moodle.org and install on a moodle 3.6 i get this error:

Plugin block_reengagement does not declare valid $plugin->component in its version.php.
    line 315 of /lib/classes/plugin_manager.php: call to debugging()
    line 335 of /lib/classes/plugin_manager.php: call to core_plugin_manager->load_present_plugins()
    line 217 of /lib/classes/plugininfo/base.php: call to core_plugin_manager->get_present_plugins()
    line 143 of /lib/classes/plugininfo/base.php: call to core\plugininfo\base->load_disk_version()
    line 97 of /lib/classes/plugininfo/base.php: call to core\plugininfo\base::make_plugin_instance()
    line 395 of /lib/classes/plugin_manager.php: call to core\plugininfo\base::get_plugins()
    line 355 of /lib/classes/plugin_manager.php: call to core_plugin_manager->get_plugins_of_type()
    line 1118 of /lib/classes/plugin_manager.php: call to core_plugin_manager->get_plugins()
    line 1239 of /admin/renderer.php: call to core_plugin_manager->missing_dependencies()
    line 212 of /admin/renderer.php: call to core_admin_renderer->missing_dependencies()
    line 679 of /admin/index.php: call to core_admin_renderer->upgrade_plugin_check_page()

and then on next page : ( it says The plugin "mod_reengagement" is installed in the wrong place $CFG->dirroot/blocks/reengagement", it was expected herer "$CFG->dirroot/mod/reengagement")

Plugin'et "mod_reengagement" er installeret et forkert sted "$CFG->dirroot/blocks/reengagement", forventet sted er "$CFG->dirroot/mod/reengagement"

Mere information om denne fejl
Debug info:
Error code: detectedmisplacedplugin
Stack trace:

    line 903 of /lib/upgradelib.php: plugin_misplaced_exception thrown
    line 520 of /lib/upgradelib.php: call to upgrade_plugins_blocks()
    line 1852 of /lib/upgradelib.php: call to upgrade_plugins()
    line 694 of /admin/index.php: call to upgrade_noncore()

You need to see if the plugin is a block or mod in the version file.

**Comment by danmarsden** [comment]
How did you install it? It is reporting that you have put it in the blocks directory instead of the mod directory where it is supposed to be.
