### ISSUE TITLE
reengagment sends notifications to teachers and students?

### ISSUE THREAD

**Issue by danmarsden** [catalyst/moodle-mod_reengagement#6]
looks like the capability "startreengagement" is used to obtain a list of people that should be sent the re-engagment notification - this is given to the student, teahcer and editingteacher roles by default. I'm not sure that is correct? - shouldn't we just be notifying students by default? - @peterbulmer thoughts?

**Comment by peterbulmer** [comment]
Yeah, I have it vaguely in my head that I was angling for 'course participants', so that things would unlock at the same rate for everyone, but as I think about it now, I have no idea why that would be needed. +1 students only.

**Comment by danmarsden** [comment]
cool - thanks, I've adjusted that now.
