### ISSUE TITLE
Deprecation warnings on M3.9

### ISSUE THREAD

**Issue by ledship** [catalyst/moodle-mod_reengagement#71]
Moodle 3.9 deprecates `user_get_participants_sql()` and `core_user_renderer->unified_filter()`.
The replacement is `\core\table\participants_search::class`.

@danmarsden thoughts on moving mod_reenagement onto this new class and putting out a MOODLE_38_STABLE release for the current codebase?

**Comment by danmarsden** [comment]
yeah - I prefer that method (branching) over trying to support multiple branches and increasing our technical debt

**Comment by ledship** [comment]
#72 will resolve this

**Comment by danmarsden** [comment]
merged. Also - note the branch name change from "master" to "main" as per our move away from using the "master" terminology.
