### ISSUE TITLE
Third Party Fields don't restore/import

### ISSUE THREAD

**Issue by Trynes** [catalyst/moodle-mod_reengagement#81]
When you restore/import the reengagement tool, the content and subject heading within the third party field does not restore/import.

Could you please add these to the restore script so teachers don't have to re-add this afterwards? Thanks.

**Comment by danmarsden** [comment]
Good spotting - not sure why that was missed! - feel free to help us work on this by submitting a pull request, otherwise we'll try to get to it at some point. Thanks!

**Comment by JoMeX20** [comment]
Same faulty behavior at reminder count field.

**Comment by danmarsden** [comment]
fixed in github now - we'll look to publish an update to the plugins db shortly.
