### ISSUE TITLE
Moodle 3.9 support?

### ISSUE THREAD

**Issue by Urpokarhu1** [catalyst/moodle-mod_reengagement#82]
Hello,

Will this plugin support Moodle 3.9?

**Comment by danmarsden** [comment]
We are not aware of any issues that would prevent this plugin working in 3.9 - please report any issues you find!

**Comment by Urpokarhu1** [comment]
Hello,

I don't see version 3.9 support here;

https://moodle.org/plugins/mod_reengagement

**Comment by danmarsden** [comment]
Yes. Typically developers only tag a version with a new moodle release if they have tested the plugin in the new release. 

We haven't run this plugin through complete testing in 3.9 but I don't expect anything to break. As mentioned above feel free to report any issues you find when using it in 3.9.
