### ISSUE TITLE
Moodle 3.9 deprecated function warnings

### ISSUE THREAD

**Issue by gemguardian** [catalyst/moodle-mod_reengagement#83]
I am testing version 3.6.2 (2019052800) on Moodle 3.9, PHP 7.3

If I bump into more issues I will drop it in this issue list. 

**Errors on page /view.php**
_Note only appearing when _debug is on Developer modus

core_user_renderer->unified_filter() is deprecated. Please use participants_filter() instead.
line 124 of /user/renderer.php: call to debugging()
line 220 of /mod/reengagement/view.php: call to core_user_renderer->unified_filter()

core_user\output\unified_filter class is deprecated. Please use \core\table\participants_search::class with table filtersets instead.
line 64 of /user/classes/output/unified_filter.php: call to debugging()
line 259 of /user/renderer.php: call to core_user\output\unified_filter->__construct()
line 220 of /mod/reengagement/view.php: call to core_user_renderer->unified_filter()

user_get_participants_sql() is deprecated. Please use \core\table\participants_search::class with table filtersets instead.
line 3584 of /lib/deprecatedlib.php: call to debugging()
line 420 of /mod/reengagement/classes/table/participants.php: call to user_get_participants_sql()
line 2019 of /lib/tablelib.php: call to mod_reengagement\table\participants->query_db()
line 266 of /mod/reengagement/classes/table/participants.php: call to table_sql->out()
line 236 of /mod/reengagement/view.php: call to mod_reengagement\table\participants->out()

user_get_participants_sql() is deprecated. Please use \core\table\participants_search::class with table filtersets instead.
line 3584 of /lib/deprecatedlib.php: call to debugging()
line 437 of /mod/reengagement/classes/table/participants.php: call to user_get_participants_sql()
line 2019 of /lib/tablelib.php: call to mod_reengagement\table\participants->query_db()
line 266 of /mod/reengagement/classes/table/participants.php: call to table_sql->out()
line 236 of /mod/reengagement/view.php: call to mod_reengagement\table\participants->out()

**Comment by danmarsden** [comment]
Looks like you're using an old version. Can you please upgrade to the version in the 'main' branch which should fix this.

**Comment by gemguardian** [comment]
Hi Dan,
It indeed fixed the issue. Sorry for not looking into Github master version, downloaded the version from Moodle.org :)
