### ISSUE TITLE
Moodle 3.9 version?

### ISSUE THREAD

**Issue by Urpokarhu1** [catalyst/moodle-mod_reengagement#84]
Hello,

When is Moodle 3.9 version going to be released?

**Comment by danmarsden** [comment]
It should work but please report any specific issues in the tracker.

**Comment by Urpokarhu1** [comment]
Hello,

When it will be released here:

https://moodle.org/plugins/mod_reengagement

we need it for our automation scripts

**Comment by danmarsden** [comment]
No assurances on when that will happen. You might want to find alternate automation scripts as you seem to be complaining about this with multiple plugins.
