### ISSUE TITLE
Support multilanguage mail texts

### ISSUE THREAD

**Issue by abias** [catalyst/moodle-mod_reengagement#9]
Hi all,

first of all, thanks for providing this very useful plugin!

I have a small feature request:
We have a multilanguage Totara site which has multiple language packs activated and provides course content in multiple languages. We would also like to use mod_reengagement for sending reminder messages in the user's preferred language. However, we have seen that mod_reengagement does not yet support Moodle's multilanguage tags (or generally: Moodle filters) in the mail body.

Would you mind adding this feature into the next version by, presumably, processing the mail body with filter_text() ?

Thanks in advance,
Alex

**Comment by danmarsden** [comment]
glad you find it useful - thanks for the feedback.

sounds like a good idea... although I'm pretty sure filter_text is deprecated and we're supposed to use format_text() - I'd be tempted to set noclean=true, trusted=true, - might also need to set nocache as it may be passing in dynamic vars.

feel free to submit a pull request with the updated code - thanks!

**Comment by abias** [comment]
Hi Dan,

thanks for your quick feedback.

You're completely right, format_text() should be used, I just typed the wrong function name but meant the right one...

We will check if we can send a pull request within reasonable time.

Thanks,
Alex

**Comment by danmarsden** [comment]
fixed in #113
