### ISSUE TITLE
Exception - The filter specified (\mod_reengagement\table\reengagement_participants_filterset) is invalid.

### ISSUE THREAD

**Issue by dsiroumi** [catalyst/moodle-mod_reengagement#94]
Hi,

I am using Moodle 3.10 and downloaded the mod_reengagement main branch from the repo.

After creating a re-engagement activity and i click to view it, i cannot seem to use the filter for firstname and surname. If i click on a letter A for example i get the following error: 

> Exception - The filter specified (\mod_reengagement\table\reengagement_participants_filterset) is invalid.
> File: ...es/external/dynamic/get.php
> Line: 215
> 
> Error code: generalexceptionmessage
> * line 215 of /lib/table/classes/external/dynamic/get.php: UnexpectedValueException thrown
> * line 261 of /lib/externallib.php: call to core_table\external\dynamic\get::execute()
> * line 81 of /lib/ajax/service.php: call to external_api::call_external_function()

Screenshot:
![image](https://user-images.githubusercontent.com/25928363/108847792-0c056d00-75d8-11eb-8fea-d8a408b15d47.png)

And secondly, if i select a user and choose an action such as send message etc on that screen, nothing happens. In the console, i see the following error:

> Uncaught Error: The table specified is not a dynamic table and cannot be updated
>     E lib/requirejs.php/1614075949/core/first.js:178
>     B /lib/requirejs.php/1614075949/core/first.js:185
>     <anonymous> /mod/reengagement/view.php?id=76:2209
>     execCb lib/javascript.php/1614075949/lib/requirejs/require.min.js:5
>     check /lib/javascript.php/1614075949/lib/requirejs/require.min.js:5
>     enable lib/javascript.php/1614075949/lib/requirejs/require.min.js:5
>     init /lib/javascript.php/1614075949/lib/requirejs/require.min.js:5
>     o /lib/javascript.php/1614075949/lib/requirejs/require.min.js:5
Screenshot:
![image](https://user-images.githubusercontent.com/25928363/108847937-47a03700-75d8-11eb-8459-a40eb9a937de.png)

Kind Regards,
Siroumi

**Comment by danmarsden** [comment]
Thanks for the report - we haven't got any clients using this plugin in 3.10 yet so this isn't high up the queue.

Pull requests are always welcome otherwise we'll probably get to this sometime! - thanks!

**Comment by exputo** [comment]
This is happening on 3.9.x as well.

**Comment by michael-vaughn** [comment]
Hey all, we're seeing this on Moodle 3.10.5. Here's the full error if it helps:

`Exception - The filter specified (\mod_reengagement\table\reengagement_participants_filterset) is invalid.
File: ...es/external/dynamic/get.php
Line: 215
Stack trace:
Error code: generalexceptionmessage
* line 215 of /lib/table/classes/external/dynamic/get.php: UnexpectedValueException thrown
* line 261 of /lib/externallib.php: call to core_table\external\dynamic\get::execute()
* line 81 of /lib/ajax/service.php: call to external_api::call_external_function()
`

**Comment by ccomincini** [comment]
Hi any news about the error? it makes the plugin unusable ...

**Comment by danmarsden** [comment]
We do have this in our backlog but pull requests are always welcome - thanks.

**Comment by danmarsden** [comment]
this was fixed in #98
