### ISSUE TITLE
Reset Completion Date 

### ISSUE THREAD

**Issue by madel1031** [catalyst/moodle-mod_reengagement#95]
Hi there. 

We have recently upgraded to Moodle 3.9.5 and are using the mod_reengagement from the main branch. 

When clicking into a reengagement, the drop down menu (Send message or Reset Completion Time) doesn't seem to be working or prompting anything even after selecting users. 
![image](https://user-images.githubusercontent.com/18272225/111831676-51eee180-88b5-11eb-8a48-15d82a95e383.png)

Also the select all and deselect all on the bottom menu are also not functioning. The square in the header of the column names does seem to be functioning as expected. 

![image](https://user-images.githubusercontent.com/18272225/111831897-a1351200-88b5-11eb-9862-c5eecce7eab7.png)

Thanks,
Madel

**Comment by jasimp** [comment]
me also facing same

**Comment by danmarsden** [comment]
most of this was fixed in #98 in the newer branches - I do think there are some newer issues related to deprecated functions in that page but easier to deal with that as a more specific report.
