### ISSUE TITLE
Cron task failure with error message 'Error reading from database'

### ISSUE THREAD

**Issue by xuangui2018** [catalyst/moodle-mod_reengagement#96]
3be6f6cc5df0:13187 Execute scheduled task: Reengagement cron task (mod_reengagement\task\cron_task)
3be6f6cc5df0:13187 ... started 20:05:07. Current memory use 10.5MB.
3be6f6cc5df0:13187 ... used 4682364 dbqueries
3be6f6cc5df0:13187 ... used 4343.7488310337 seconds
3be6f6cc5df0:13187 Scheduled task failed: Reengagement cron task (mod_reengagement\task\cron_task),Error reading from database

**Comment by danmarsden** [comment]
Thanks @xuangui2018 - as mentioned internally, please provide:
* Moodle version in use
* Re-engagment plugin version in use/
* Full debug trace using developer debug or error logs.

thanks,

**Comment by xuangui2018** [comment]
Hey Dan,

I am closing this issue as the error mentioned above most probably due to moodle version.

Regards,
Xuan
